import os

CAMINHO_EXEL = "CAMINHO_DO_EXCEL"
NUMERO_PAGINA_ALVO = "1"

NOME_COLUNA_ALVO = "Matrícula"

NOME_XLSX = "NOME_DO_ARQUVIO.xlsx"

PAGINA_UM_TABELA = [268.122,24.246,795.441,432.565]

PASTA_SAIDA_CSV = 'CAMINHO_ARQUIVO_SAIDA'

ARQUIVO_CVS = os.path.join(PASTA_SAIDA_CSV,"ARQUIVO_EXTRACAO.csv")
